<a href="https://colab.research.google.com/github/Heet06/MLUP001/blob/main/Week-4/data_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preparation

In [1]:
import pandas as pd
import numpy as np

### Load data

In [3]:
demoDetails = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/demoDetails.csv", index_col=0)
acDetails = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/acDetails.txt", sep="\t")
serviceDetails = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/datasets/serviceDetails.csv", index_col=0)

By setting `index_col=0`, 1st column will be the index column

### Data Wrangling

- We are interested in merging acDetails, demoDetails and serviceDetails
- Before merging we need to make necesarry checks!
- What are mandatory checks before merging?
  1. Are there any duplicate records?
  2. Whether the customer ID common across all the files?

#### **1. Are there any duplicate records?**

In [6]:
# Are there any duplicate records?
print(len(demoDetails))
len(np.unique(demoDetails['customerID']))

251

250

In [7]:
print(len(acDetails))
len(np.unique(acDetails['customerID']))

251

250

In [8]:
print(len(serviceDetails))
len(np.unique(serviceDetails['customerID']))

251

250

Yes, there is one duplicate record across all the three dataframes

In [10]:
# To determine the duplicate records 'duplicated()' method can be used

demoDetails.duplicated(subset=['customerID'], keep=False)

# This method returns a boolean series with True value for each duplicated row

1      False
2      False
3      False
4      False
5      False
       ...
247    False
248    False
249    False
250    False
251     True
Length: 251, dtype: bool

In [11]:
# So now let's subset the rows and look at the duplications

In [12]:
demoDetails[demoDetails.duplicated(['customerID'], keep=False)]

     customerID gender  SeniorCitizen Partner Dependents
46   9067-SQTNS   Male            0.0     Yes        Yes
251  9067-SQTNS   Male            0.0     Yes        Yes

In [14]:
acDetails[acDetails.duplicated(['customerID'], keep=False)]

,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
46,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.6,926.0
251,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.6,926.0

In [15]:
acDetails[acDetails.duplicated(['customerID'], keep=False)]

,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
46,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.6,926.0
251,9067-SQTNS,44,One year,No,Bank transfer (automatic),20.6,926.0

In [18]:
# Removing Duplicate Records

demoDetails = demoDetails.drop_duplicates()

acDetails = acDetails.drop_duplicates()

serviceDetails = serviceDetails.drop_duplicates()

By default the first occurence of duplicate rows is kept and subsequent occurence are removed.

`keep` parameter can be used to:
- 'last': keep the last occurence
- 'first': keep the first occurence
- 'False': all occurences other than last one are removed

#### **2. Whether customerID is common across all the files?**

syntax: `dataframe1.equals(dataframe2)`

In [20]:
acDetails.customerID.equals(demoDetails.customerID)

True

In [21]:
serviceDetails.customerID.equals(demoDetails.customerID)

True

In [22]:
acDetails.customerID.equals(serviceDetails.customerID)

True

customerID in all files/datasets are identical.

### Joining three dataframes

Syntax: `pd.merge(df1, df2, on=[ColumnName], how='inner')`

In [25]:
churn = pd.merge(demoDetails, acDetails, on = 'customerID')

churn = pd.merge(churn, serviceDetails, on = 'customerID')

churn1 = churn.copy()

churn.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Churn'],
      dtype='object')

#### Data Exploration

In [26]:
churn1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        250 non-null    object
 1   gender            250 non-null    object
 2   SeniorCitizen     245 non-null    float64
 3   Partner           250 non-null    object
 4   Dependents        250 non-null    object
 5   tenure            250 non-null    object
 6   Contract          250 non-null    object
 7   PaperlessBilling  250 non-null    object
 8   PaymentMethod     250 non-null    object
 9   MonthlyCharges    240 non-null    float64
 10  TotalCharges      235 non-null    float64
 11  PhoneService      250 non-null    object
 12  MultipleLines     250 non-null    object
 13  InternetService   250 non-null    object
 14  OnlineSecurity    250 non-null    object
 15  OnlineBackup      250 non-null    object
 16  DeviceProtection  250 non-null    object
 17  TechSupport       250 non-null    object
 18  StreamingTV       250 non-null    object
 19  StreamingMovies   250 non-null    object
 20  Churn             250 non-null    object
dtypes: float64(3), object(18)
memory usage: 41.1+ KB

Points to note:
- 'tenure' has been read as object
- 'SeniorCitize' has been read as float64 instead of object
- Missing values present in few variables

In [ ]:
# unique() finds the unique elements of an array
np.unique(churn['tenure'], return_counts=True)